### ISSUE TITLE
Are you still maintaining this repo?

### ISSUE THREAD

**Issue by mkay581** [finn-no/carousel-js#25]
Hello,

Are you still maintaining this repo as a bower package?
I'd like to discuss possibly taking this over on my new Carousel package I have here:
https://github.com/mkay581/carousel-module

Feel free to take a look and let me know your thoughts.

Thanks,

**Comment by gregersrygg** [comment]
We're not maintaining this anymore, and I'm not aware of anyone using it as a bower-dependency. Can try to unregister the package on Bower to free up the name - if I can find someone who has the password :grimacing:

**Comment by gregersrygg** [comment]
It's unregistered from bower now, so you're free to register carousel-module as carousel-js if you want.

**Comment by mkay581** [comment]
thanks a lot! Just registered it under new name. :)

**Comment by gregersrygg** [comment]
You're welcome :)

**Comment by mkay581** [comment]
Do you mind allowing me to take over this repo also? I figured it may be helpful to everyone who is currently subscribed, watching, and stargazing.

**Comment by gregersrygg** [comment]
We (and maybe others) still use this project even though it's not actively maintained, with npm as the package manager. I would be happy to add contributors to maintain this project, but it sounds more like you'd like to promote your own. Sorry, but you have to find other ways to do that :wink:

**Comment by mkay581** [comment]
No worries, I appreciate your time.
